//
// Created by Ching-An Tsai on 09/04/2018.
//

#ifndef PA8_DATAANALYSISUSINGBINARYSEARCHTREES_TRANSACTIONNODE_H
#define PA8_DATAANALYSISUSINGBINARYSEARCHTREES_TRANSACTIONNODE_H


class TransactionNode {

};


#endif //PA8_DATAANALYSISUSINGBINARYSEARCHTREES_TRANSACTIONNODE_H
